---
- hosts: webservers
  become: yes
  tasks:
  - name: install git
    apt: 
     name: git
     state: present
    tags: 1st
    when: "{{UB}}"

  - name: install tree
    apt:
     name: tree
     state: present
    tags: 2nd
    when: "{{Red}}"
