---
- name: create folder
  file:
   path: /opt/tomcat
   state: directory

- name: extract tomcat
  command:
   cmd: sudo tar xzvf /home/nag/apache-tomcat-8.5.47.tar.gz -C /opt/tomcat --strip-components=1
   creates: /opt/tomcat/LICENSE