---
- include_tasks: javainstall.yml
- include_tasks: group.yml
- include_tasks: tomdown.yml
- include_tasks: extract.yml
- include_tasks: config.yml
- include_tasks: permision.yml
- include_tasks: tomstart.yml
# tasks file for tomsetup