---
- name: mount the directory
  mount:
   path: /nfs/general
   src: 172.31.29.73:/var/nfs/general
   fstype: mounted
   opts: bind
   state: present
   
- name: mount home
  mount:
   path: /nfs/home
   src: 172.31.29.73:/nfs/home
   fstype: mounted
   opts: bind
   state: present